---
name: README Info Update

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  update-readme:
    name: GitHub README Generator
    runs-on: ubuntu-latest
    steps:
      - name: GitHub README Generator
        uses: th3c0d3br34ker/github-readme-info@1.0.2
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          TIMEZONE: "America/Toronto"
          SHOW_LINES_OF_CODE: "False"
          SHOW_PROFILE_VIEWS: "True"
          SHOW_DAILY_COMMIT: "False"
          SHOW_WEEKLY_COMMIT: "False"
          SHOW_LANGUAGE: "True"
          SHOW_TOTAL_CONTRIBUTIONS: "False"
